version: '2'
services:
    app-postgresql:
        image: postgres:10.1
        # volumes:
        #     - ~/volumes/jhipster/App/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=App
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
